import { getDb, auditLog, cases } from "@dialog/db";
import { and, asc, eq } from "drizzle-orm";
import type { CaseState } from "@dialog/config";

/**
 * WHAT WAS DONE IN THE CUSTOMER'S NAME, WRITTEN FOR THE CUSTOMER.
 *
 * The audit trail has been complete for months and visible only to staff. The
 * pre-launch checklist asks for something different — "يعرّض سجلاً مفهوماً لما
 * نفذه باسم المتعامل", an understandable log of what the assistant did on their
 * behalf — and the action-log artefact fixes its schema: who requested it, who
 * executed it, whether consent was required and what its status was, what was
 * done in the customer's name, the result, the reference, and the next step.
 *
 * The PO's answer on 16 September was "all of that is mentioned as part of the
 * journey" (FB-1738), and that is half right: the assistant narrates each step
 * as it happens and the panel mirrors the case. What neither gives is the thing
 * the artefact asks for — the whole account in one place, after the fact, in the
 * customer's own language, which is what somebody wants when they come back a
 * week later and ask what exactly was sent in their name.
 *
 * Built from the audit rows the system already writes. Nothing new is recorded
 * for it, and nothing here is generated by the model: if an action is not in the
 * audit log it does not appear, and an action that failed says so.
 */

export interface ActionLogEntry {
  /** ISO, so the client renders it in the reader's own timezone. */
  at: string;
  /** Who asked for it. The customer, or the system acting on a schedule. */
  requestedBy: string;
  /** Who carried it out — the assistant, or the entity's own system. */
  executedBy: string;
  /** What was done, in plain words. */
  action: string;
  /** Whether it needed the customer's approval, and what that approval was. */
  consent: string;
  /** What came back. */
  result: "ok" | "failed" | "refused";
  /** The reference a customer can quote, when the action produced one. */
  reference?: string;
}

const STR = {
  en: {
    you: "You", assistant: "The assistant", system: "The system",
    entity: (e: string) => e,
    notRequired: "Not required",
    given: "Given",
    declined: "Declined",
    submitted: (e: string) => `Submitted your request to ${e}`,
    document: (d: string) => `Attached ${d} to your request`,
    documentFailed: (d: string) => `Tried to attach ${d} to your request`,
    paymentStarted: (a: string) => `Opened a secure payment for ${a}`,
    paymentTaken: (a: string) => `Payment of ${a} received`,
    emailed: (to: string) => `Emailed your confirmation to ${to}`,
    emailFailed: (to: string) => `Tried to email your confirmation to ${to}`,
    callback: "Arranged a callback with the team, and passed on everything collected so far",
    lookup: (e: string) => `Looked up your record with ${e}`,
    consentDeclined: (what: string) => `You declined ${what}, so it was not carried out`,
    survey: "Offered you the government satisfaction survey",
    opsNotified: "Told the branch team what needs arranging",
  },
  ar: {
    you: "أنت", assistant: "المساعد", system: "النظام",
    entity: (e: string) => e,
    notRequired: "غير مطلوبة",
    given: "مُعطاة",
    declined: "مرفوضة",
    submitted: (e: string) => `تم إرسال طلبك إلى ${e}`,
    document: (d: string) => `تم إرفاق ${d} بطلبك`,
    documentFailed: (d: string) => `محاولة إرفاق ${d} بطلبك`,
    paymentStarted: (a: string) => `تم فتح صفحة دفع آمنة بمبلغ ${a}`,
    paymentTaken: (a: string) => `تم استلام دفعة بمبلغ ${a}`,
    emailed: (to: string) => `تم إرسال التأكيد إلى ${to}`,
    emailFailed: (to: string) => `محاولة إرسال التأكيد إلى ${to}`,
    callback: "تم ترتيب اتصال من الفريق مع كل ما تم جمعه",
    lookup: (e: string) => `تم الاستعلام عن سجلك لدى ${e}`,
    consentDeclined: (what: string) => `رفضتَ ${what}، لذلك لم يُنفَّذ`,
    survey: "تم عرض استبيان رضا المتعاملين الحكومي",
    opsNotified: "تم إبلاغ فريق الفرع بما يلزم ترتيبه",
  },
} as const;

/** The actions a customer has any business reading. Everything else is ours. */
const SHOWN = new Set([
  "case_submitted",
  "integration_write",
  "integration_call_failed",
  "sf_document_attached",
  "sf_document_failed",
  "payment_initiated",
  "email_sent",
  "email_send_failed",
  "confirmation_email_sent",
  "confirmation_email_failed",
  "escalation_created",
  "consent_declined",
  "survey_offered",
  "ops_notified",
]);

const str = (v: unknown) => (v === null || v === undefined ? "" : String(v).trim());
const words = (key: string) => key.replace(/[_-]+/g, " ").trim();

export interface AuditRow {
  action: string;
  actor: string;
  payload: Record<string, unknown>;
  createdAt: Date | string;
}

/**
 * The log, from rows the system already wrote.
 *
 * Pure on purpose: the readiness probe runs it against fabricated rows, so the
 * criterion is evidenced by executing this rather than by anyone asserting the
 * page exists.
 */
export function renderActionLog(
  rows: AuditRow[],
  opts: { locale?: string; entity?: string; caseReference?: string | null; amount?: string | null } = {}
): ActionLogEntry[] {
  const s = STR[opts.locale === "ar" ? "ar" : "en"];
  const entity = opts.entity?.trim() || (opts.locale === "ar" ? "الجهة" : "the entity");
  const out: ActionLogEntry[] = [];

  for (const row of rows) {
    if (!SHOWN.has(row.action)) continue;
    const p = (row.payload ?? {}) as Record<string, unknown>;
    const at = new Date(row.createdAt).toISOString();
    const base = { at, requestedBy: s.you, executedBy: s.assistant, consent: s.notRequired, result: "ok" as const };

    switch (row.action) {
      case "case_submitted":
        out.push({ ...base, action: s.submitted(entity), consent: s.given, reference: str(p.reference) || opts.caseReference || undefined });
        break;
      case "integration_write":
        // A write that is not the submission itself: the entity's own system did it.
        out.push({ ...base, executedBy: entity, action: s.submitted(entity), consent: s.given, reference: opts.caseReference || undefined });
        break;
      case "integration_call_failed":
        out.push({ ...base, executedBy: entity, action: s.lookup(entity), result: "failed" });
        break;
      case "sf_document_attached":
        out.push({ ...base, action: s.document(words(str(p.key) || str(p.label))), consent: s.given });
        break;
      case "sf_document_failed":
        out.push({ ...base, action: s.documentFailed(words(str(p.key) || str(p.label))), consent: s.given, result: "failed" });
        break;
      case "payment_initiated":
        out.push({ ...base, action: s.paymentStarted(str(p.amount) ? `${str(p.amount)}` : (opts.amount ?? "")), consent: s.given, reference: str(p.reference) || undefined });
        break;
      case "email_sent":
      case "confirmation_email_sent":
        out.push({ ...base, action: s.emailed(str(p.to)), consent: s.given });
        break;
      case "email_send_failed":
      case "confirmation_email_failed":
        out.push({ ...base, action: s.emailFailed(str(p.to)), consent: s.given, result: "failed" });
        break;
      case "escalation_created":
        out.push({ ...base, action: s.callback, consent: s.given, reference: str(p.reference) || undefined });
        break;
      case "consent_declined":
        out.push({ ...base, action: s.consentDeclined(words(str(p.key) || str(p.what))), consent: s.declined, result: "refused" });
        break;
      case "survey_offered":
        out.push({ ...base, executedBy: s.system, action: s.survey });
        break;
      case "ops_notified":
        out.push({ ...base, executedBy: s.system, action: s.opsNotified, consent: s.given });
        break;
    }
  }

  // Oldest first: a log is read forwards. Duplicates of the same action at the
  // same second are one thing that happened, not two.
  const seen = new Set<string>();
  return out
    .sort((a, b) => a.at.localeCompare(b.at))
    .filter((e) => {
      const key = `${e.at.slice(0, 19)}|${e.action}`;
      if (seen.has(key)) return false;
      seen.add(key);
      return true;
    });
}

/** The log for one conversation, for the customer reading it. */
export async function customerActionLog(
  conversationId: string,
  opts: { locale?: string; entity?: string } = {}
): Promise<{ entries: ActionLogEntry[]; caseReference: string | null }> {
  const db = getDb();
  const rows = await db
    .select({ action: auditLog.action, actor: auditLog.actor, payload: auditLog.payload, createdAt: auditLog.createdAt })
    .from(auditLog)
    .where(eq(auditLog.conversationId, conversationId))
    .orderBy(asc(auditLog.createdAt))
    .limit(300);
  const [row] = await db
    .select({ state: cases.state })
    .from(cases)
    .where(and(eq(cases.conversationId, conversationId)))
    .limit(1);
  const state = row?.state as CaseState | undefined;
  const caseReference = str(state?.referenceLabel) || str(state?.reference) || null;
  return {
    entries: renderActionLog(rows as AuditRow[], { ...opts, caseReference }),
    caseReference,
  };
}
